### PR TITLE
Updates to GithubPr and GithubCommit

### PR DESCRIPTION
**Pull request by idilhanhan**
Updated GithubPr to not include comments as a necessity to be counted as a reviewer (Issue: https://github.com/LaraMerdol/source-classes/issues/1)
Updates GithubCommit with a get co-authors function (Issue: https://github.com/LaraMerdol/source-classes/issues/2)
And minor reformatting changes

### CODE REVIEW

**Comment by idilhanhan** [comment]
@LaraMerdol I could not run the tests on my local env, can you take a look when you have the time please?

**Comment by LaraMerdol** [comment]
I have made changes related to adding author-filed check-in history after pr. Therefore, the version changed I have merged changes (just the version changed from 1.5 to 1.7). @idilhanhan

**Comment by idilhanhan** [comment]
@LaraMerdol got it, I updated the version for these changes now 👍

**Comment by idilhanhan** [comment]
Related PR: https://github.com/idilhanhan/software-artifact-analyzer-configuration/pull/8

**Review by LaraMerdol — APPROVED** [review]
It looks fine to me.

**Pull request merged**
